version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://usergolang:admin1234@db:5432/userdb?sslmode=disable
    depends_on:
      - db
    command: ["./main"]

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=usergolang
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=userdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: