version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: usergolang
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usergolang -d userdb"]
      interval: 2s
      timeout: 5s
      retries: 30


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://usergolang:admin1234@db:5432/userdb?sslmode=disable
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=postgres://usergolang:admin1234@db:5432/userdb?sslmode=disable
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=usergolang
    depends_on:
      db:
        condition: service_healthy
    tty: true

volumes:
  pgdata:
