version: "3.9"

services:
  db:
    image: postgres:16
    container_name: user-go-db
    environment:
      POSTGRES_USER: usergolang
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: user-go-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://usergolang:admin1234@db:5432/userdb?sslmode=disable
    command: ["go", "test", "./..."]
    volumes:
      - .:/app
